# Generated by Django 2.0.3 on 2018-04-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permission_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='UserPermission',
        ),
    ]
